---
title: "Optimization Sim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
initial <- InitialProbPattern(pattern_data_sim,freq_vec_sim)
transition <- TransitionProbPattern(pattern_data_sim,freq_vec_sim)

LogLike <- function(init_0,init_1) {
  
  # ExpectedW <- function(data, ind, pi0, pi1, state){
  #   stayer_vec <- c(pi0,pi1)
  #   likelihood <- CalcIndLikelihood(data,ind,initial,transition,stayer_vec)
  #   W_i <- 0
  #   
  #   if (max(data[ind,], na.rm = T) == state & min(data[ind,], na.rm = T) == state){
  #     if (state == 0 & state == min(data[ind,], na.rm = T)){
  #       W_i <- stayer_vec[1] * log(stayer_vec[1]) / likelihood
  #     } else if (state == 1 & state == min(data[ind,], na.rm = T)){
  #       W_i <- stayer_vec[2] * log(stayer_vec[2]) / likelihood
  #     }
  #   }
  #   return(W_i)
  # }
  

  LogLikeInd <- function(init_0, init_1){
    L_total <- 0
    for (ind in 1:dim(pattern_data_sim)[1]){
      L_current <- 0
      # L <- L + -(ExpectedW(pattern_data_sim,ind,pi0,pi1,0) + ExpectedW(pattern_data_sim,ind,pi0,pi1,1))
      # L <- L + -( (1 - ExpectedW(pattern_data_sim,ind,pi0,pi1,0) + ExpectedW(pattern_data_sim,ind,pi0,pi1,1)) *
      #               (   log(1.001 - pi0 - pi1) + (1 - pattern_data_sim[ind,1])*log(init_0) + pattern_data_sim[ind,1]*log(init_1) ) )
      L_current <- L_current + -((1 - pattern_data_sim[ind,1])*log(init_0) + pattern_data_sim[ind,1]*log(init_1))
      
      L_current <- L_current  * freq_vec_sim[ind]
      L_total <- L_total + L_current
    }
    return(L_total)
  }
  
  
  L <- LogLikeInd(init_0,init_1) 
    
}

LogLikeb <- function(x) LogLike(x[1],x[2])

equal <- function(x) x[1] + x[2]
```


```{r}
#https://stackoverflow.com/questions/30494083/r-optimization-with-equality-and-inequality-constraints
#?solnp()
library(Rsolnp)
solnp(c(.5,.5), #Starting Vals
      LogLikeb, #funtion to optimize
      eqfun = equal, #equality funtcion
      eqB = 1, #equality constant 
      LB = c(0,0), #lower bound
      UB = c(1,1)) #upper bound
```