---
title: "Side Project Sim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
init_full_true_og <- c(0.75,.25)
tran_full_true_og <- matrix(0,2,2)
tran_full_true_og[1,1] <- .9
tran_full_true_og[1,2] <- .1
tran_full_true_og[2,2] <- .95
tran_full_true_og[2,1] <- .05
```

```{r}
GenerateAll <- function(n,t,p){
  stayer_mat_true <- GenerateMS(n,p)
  data_mat <- matrix(0L, nrow = n, ncol = t)
  
  for (i in 1:n){
    if (sum(stayer_mat_true[i,]) == 0){
      data_mat[i,1] <- which(rmultinom(1,1,init_full_true_og) == 1) - 1
    } else if (stayer_mat_true[i,2] == 1){
      data_mat[i,1] <- 1
    }
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (stayer_mat_true[i,2] == 1){
        data_mat[i,] <- 1
      } else if(sum(stayer_mat_true[i,]) == 0){
        p_current <- tran_full_true_og[data_mat[i,j-1]+1,]
        data_mat[i,j] <- which(rmultinom(1,1,p_current) == 1) - 1
      }
    }
  }
  return(list(data_mat,stayer_mat_true))
}
```

```{r}
GenerateMS <- function(n,p){
  num_of_stayers <- round(p*n)
  num_of_stayers_0 <- round(num_of_stayers/2)
  num_of_stayers_1 <- num_of_stayers - num_of_stayers_0
  
  stayer_mat <- matrix(0,n,2)
  for (i in 1:num_of_stayers_0){
    stayer_mat[i,1] <- 1
  }
  for (i in (num_of_stayers_0+1):(num_of_stayers_1 + num_of_stayers_0)){
    stayer_mat[i,2] <- 1
  }
  return(stayer_mat)
}
```

```{r}
n <- 1000
t <- 21
p <- .5
p<- 0
data_full_sim <- GenerateAll(n,t,p)
data_sim <- data_full_sim[[1]]
stayer_mat_sim <- data_full_sim[[2]]

# data_sim[,2:5] <- NaN
# data_sim[,7:10] <- NaN
# data_sim[,12:15] <- NaN
# data_sim[,17:20] <- NaN

all_patterns_sim <- GetPatterns(data_sim)
unique_patterns_sim <- as.data.frame(table(all_patterns_sim))

pattern_list_sim <- Pattern2Data(unique_patterns_sim)
pattern_data_sim <- pattern_list_sim[[1]]
freq_vec_sim <- pattern_list_sim[[2]]
#stayer_vec_sim <- pattern_list[[3]]
```

```{r}
stayer_vec_sim <- matrix(0,length(freq_vec_sim),2)
for (i in 1:dim(pattern_data_sim)[1]){
  if (0 %in% pattern_data_sim[i,]){
    zero_bool <- T
  } else {
    zero_bool <- F
  }
  
  if (1 %in% pattern_data_sim[i,]){
    one_bool <- T
  } else {
    one_bool <- F
  }
  
  if (zero_bool & !one_bool){
    stayer_vec_sim[i,1] <- 1/2
  } else if (!zero_bool & one_bool){
    stayer_vec_sim[i,2] <- 1/2
  }
}
```


```{r}
init <- InitialProbPattern(pattern_data_sim,freq_vec_sim)
tran <- TransitionProbPattern(pattern_data_sim,freq_vec_sim)
stayer_vec_sim <- CalcStayer(pattern_data_sim,tran, freq_vec_sim)
stayer_mat_sim <- Vec2Mat(pattern_data_sim,stayer_vec_sim)
old_likelihood <- CalcLikelihoodPattern(pattern_data_sim,init,tran,freq_vec_sim,stayer_mat_sim)


init <- CalcYiPattern(pattern_data_sim,1,init,tran,freq_vec_sim,stayer_mat_sim)
tran <- CalcTransitionPattern(pattern_data_sim,init,tran,freq_vec_sim,stayer_mat_sim)
stayer_vec_sim <- CalcStayer(pattern_data_sim,tran, freq_vec_sim, stayer_vec_sim)
stayer_mat_sim <- Vec2Mat(pattern_data_sim,stayer_vec_sim)
likelihood <- CalcLikelihoodPattern(pattern_data_sim,init,tran,freq_vec_sim,stayer_mat_sim)

print(likelihood - old_likelihood)

while (abs(likelihood - old_likelihood) > 0.001){
  old_likelihood <- likelihood

  init <- CalcYiPattern(pattern_data_sim,1,init,tran,freq_vec_sim,stayer_mat_sim)
  tran <- CalcTransitionPattern(pattern_data_sim,init,tran,freq_vec_sim,stayer_mat_sim)
  stayer_vec_sim <- CalcStayer(pattern_data_sim,tran, freq_vec_sim, stayer_vec_sim)
  stayer_mat_sim <- Vec2Mat(pattern_data_sim,stayer_vec_sim)
  likelihood <- CalcLikelihoodPattern(pattern_data_sim,init,tran,freq_vec_sim,stayer_mat_sim)
  
  print(likelihood - old_likelihood)
}

freq_vec_sim[1] * stayer_vec_sim[1] 
freq_vec_sim[length(freq_vec_sim)] * stayer_vec_sim[2]

p * n * 1/2
```

```{r}
stayer_mat <- matrix(0,dim(pattern_data_sim)[1],2)
stayer_mat[1,1]<- 250 / freq_vec_sim[1]
stayer_mat[dim(pattern_data_sim)[1],2] <- 250 / freq_vec_sim[length(freq_vec_sim)]
```


