---
title: "Side Project Data Setup"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
state_data <- read.csv("State_residence_Dec112018.csv")
year_data <- read.csv("year registry state.csv")
dates <- as.matrix(state_data[,6:9])
states <- as.matrix(state_data[,10:13])
diagnosed <- as.vector(state_data[,15])

#min should be 83
min_date <- 83
#max is 14 but extrapolating to 16
max_date <- 16

GetDate <- function(date){
  if (date < 20){return(date+2000)} 
  else {return(date+1900)} 
}

catch_data <- matrix(NaN, dim(dates)[1], (GetDate(max_date) - GetDate(min_date) + 1))
colnames(catch_data) <- c(GetDate(min_date):GetDate(max_date))

for (i in 1:dim(dates)[1]){
  for (j in 1:dim(dates)[2]){
    if (!is.na(dates[[i,j]])){
      state_bool <- 0 
      year <- GetDate(as.integer(substr(dates[[i,j]],(nchar(dates[[i,j]]) - 1),nchar(dates[[i,j]]))))
      
      if (!is.na(states[[i,j]])){
        if (states[[i,j]] %in% year_data$state){
          row_vals <- year_data[year_data$state == states[[i,j]],]
          min_val <- row_vals[1,2]
          max_val <- row_vals[1,3]
          if (year > min_val & year < max_val){
            state_bool <- 2
            #make the following state_bool 2 if want to categorize by year
          } else {state_bool <- 2}
          #make the following state_bool 2 if want to categorize by state
        } else {state_bool <- 1}
      }
      
      if (state_bool == 2){
        adj_year <- year - GetDate(min_date) + 1
        catch_data[i,adj_year] <- 1
      }
      
      if (state_bool == 1){
        adj_year <- year - GetDate(min_date) + 1
        catch_data[i,adj_year] <- 0
      }
      
    }
  }
  if (!is.na(diagnosed[i])){
    diagnosed_date <- GetDate(as.integer(substr(diagnosed[i],(nchar(diagnosed[i]) - 1),nchar(diagnosed[i]))))
    adj_diagnosed_date <- diagnosed_date - GetDate(min_date) + 1
    catch_data[i,adj_diagnosed_date] <- 1
  }
  
  
  
  
}
```

```{r}
GetPatterns <- function(states,stayer_mat){
  library(plyr)
  options(scipen = 999)
  vals <- rep(NaN,dim(states)[1])
  for (i in 1:dim(states)[1]){
    val <- ""
    for(j in 1:dim(states)[2]){
      if (!is.na(states[i,j])){
        states_val <- states[i,j] 
      } else {
        states_val <- 2 
      }
      val <- paste0(val, states_val)
    }
    if (!missing(stayer_mat)){
      val <- paste0(val,stayer_mat[i])
    }
    
    vals[i] <- val
  }
  return(vals)
}
```

```{r}
Pattern2Data <- function(unique_patterns, stayer_mat){
  time_length <- nchar(as.character(unique_patterns$all_patterns[[1]]))
  n <- dim(unique_patterns)[1]
  state_mat <- matrix(NaN,n,time_length)
  freq_vec <- numeric(n)
  stayer_mat <- numeric(n)
  for (i in 1:n){
    freq_vec[i] <- unique_patterns$Freq[[i]]
    pattern <- unique_patterns$all_patterns[[i]]
    for (time in 1:time_length){
      new_val <- as.integer(substr(pattern, time,time))
      if (new_val == 2){
        new_val <- NaN
      }
      state_mat[i,time] <- new_val
    }
  }
  if (!missing(stayer_mat)){
    return(list(state_mat, freq_vec,stayer_mat))
  }
  return(list(state_mat, freq_vec))
}

```

```{r}

all_patterns <- as.data.frame(GetPatterns(catch_data))
unique_patterns <- as.data.frame(table(all_patterns))

pattern_list <- Pattern2Data(unique_patterns)
state_pattern <- pattern_list[[1]]
freq_vec <- pattern_list[[2]]

```

```{r}
test <- numeric(dim(dates)[1])
for (i in 1:dim(dates)[1]){
  if (!is.na(dates[,4][i])){
    test[i] <- as.integer(substr(dates[,4][i],nchar(dates[,4][i]),nchar(dates[,4][i])))
  }
  
  if (i %% 10000 == 0){print(i)}
  
}
```


