---
title: "Side Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
numOfStates <- function(data){
  return(c(0:1))
}
```

```{r}
Classification <- function(x_val, y_val){
  if (x_val == y_val){return(1)}
  else {return(0)}
}
```

```{r}
Normalize <- function(data){
  for (i in 1:dim(data)[1]){
    if (sum(data[i,],na.rm = TRUE) != 0){
      data[i,] <- data[i,]/sum(data[i,])
    }
  }
  return(data)
}
```

```{r}
GetPatterns <- function(states,stayer_mat){
  library(plyr)
  options(scipen = 999)
  vals <- rep(NaN,dim(states)[1])
  for (i in 1:dim(states)[1]){
    val <- ""
    for(j in 1:dim(states)[2]){
      if (!is.na(states[i,j])){
        states_val <- states[i,j] 
      } else {
        states_val <- 2 
      }
      val <- paste0(val, states_val)
    }
    if (!missing(stayer_mat)){
      val <- paste0(val,stayer_mat[i])
    }
    
    vals[i] <- val
  }
  return(vals)
}
```

```{r}
Pattern2Data <- function(unique_patterns, stayer_mat){
  #SHOULD BE 32
  time_length <- nchar(as.character(unique_patterns$all_patterns[[1]]))
  n <- dim(unique_patterns)[1]
  state_mat <- matrix(NaN,n,time_length)
  freq_vec <- numeric(n)
  stayer_mat <- numeric(n)
  for (i in 1:n){
    freq_vec[i] <- unique_patterns$Freq[[i]]
    pattern <- unique_patterns$all_patterns[[i]]
    
    if (!missing(stayer_mat)){
      #stayer_mat[i] <- as.integer(substr(pattern, years_to_impute,years_to_impute))
    }
    
    for (time in 1:time_length){
      new_val <- as.integer(substr(pattern, time,time))
      if (new_val == 2){
        new_val <- NaN
      }
      state_mat[i,time] <- new_val
    }
  }
  if (!missing(stayer_mat)){
    return(list(state_mat, freq_vec,stayer_mat))
  }
  return(list(state_mat, freq_vec))
}

```

```{r}
InitialProbPattern <- function(data, freq_vec,stayer_mat, time){
  if (missing(time)){
    time <- 1
  }
  k <- numOfStates(data)
  init_prob <- numeric(length(k))
  
  for (i in 1:dim(data)[1]){
    if (!is.na(data[i,1])){
      if (!missing(stayer_mat)){
        init_prob[data[i,1] + 1] <- (init_prob[data[i,1]+1] + freq_vec[i]) * (1 - stayer_mat[[i]])
      } else {
        init_prob[data[i,1] + 1] <- (init_prob[data[i,1]+1] + freq_vec[i])
      }
    }
  }
  
  return(init_prob/sum(init_prob))
}
```

```{r}
TransitionProbPattern <- function(data, freq_vec){
  
  n <- dim(data)[1]
  length <- dim(data)[2]
  k <- numOfStates(data)
  transition <- matrix(0L, nrow = length(k), ncol = length(k))

  for (i in 1:n){
    ind <- data[i,]
    ind <- ind[!is.na(ind)]
    if (length(ind) > 1){
      for (j in 1:(length(ind) - 1)){
        transition[which(ind[[j]] == k),which(ind[[j+1]] == k)] = (transition[which(ind[[j]] == k),which(ind[[j+1]] == k)] + freq_vec[i])
      }
    }
      
  }

  return(Normalize(transition))
}

```

```{r}
#JASA paper method 
ForwardIter <- function(data,time,individual,initial_probabilities,transition){
  k <- numOfStates(data)
  alpha_matrix<-vector("list",time)
  alpha_i <- numeric(length(k))
  
  for (i in 1:time){
    alpha_matrix[[i]] <- alpha_i
  }
  
  for (i in 1:length(k)){
    if (!is.na(data[individual,1])){
      alpha_matrix[[1]][i] <- initial_probabilities[i] * Classification(data[individual,1], k[i])
    } else {
      alpha_matrix[[1]][i] <- initial_probabilities[i]
    }
  }
  if (time == 1){
    return(alpha_matrix)
  }

  for (i in 2:time){
    for (j in 1:length(k)){
      if (!is.na(data[individual,i])){
        alpha_matrix[[i]][j] <- (alpha_matrix[[i-1]] %*% transition[,j]) * Classification(data[individual,i], k[j])
      } else {
        alpha_matrix[[i]][j] <- (alpha_matrix[[i-1]] %*% transition[,j])
      }
    }
  }
  return(alpha_matrix)
}
```

```{r}
#JASA method 
BackwardIter <- function(data,time,individual,transition){
  k <- numOfStates(data)
  length <- dim(data)[2]
  beta_i <- numeric(length(k))
  misclass_vector <- numeric(length(k))
  beta_matrix<-vector("list",length)
  
  for (i in 1:length){
    beta_matrix[[i]] <- beta_i
  }
  
  for (i in 1:length(k)){
    beta_matrix[[length]][i] <- 1
  }
  if (time == length){
    return(beta_matrix)
  }
  for (i in (length-1):time){
    if (!is.na(data[individual,i+1])){
      for (l in 1:length(k)){
        misclass_vector[l] <- Classification(data[individual,i+1],k[l])
      }
      for (j in 1:length(k)){
        beta_matrix[[i]][j] <- sum(beta_matrix[[i+1]] * transition[j,] * misclass_vector,na.rm = TRUE)
      }
    } else {
      for (j in 1:length(k)){
        if (sum(beta_matrix[[i+1]]) == length(k)){
          beta_matrix[[i]][j] <- 1
        } else {
         beta_matrix[[i]][j] <- sum(beta_matrix[[i+1]] * transition[j,]) 
        }
      }
    }
  }
  
  return(beta_matrix)
}
```

```{r}
YgivenXi <- function(data, time, individual, initial_probabilities, transition,stayer_mat){
  max_time <- dim(data)[2]
  forward <- ForwardIter(data,max_time,individual,initial_probabilities, transition)
  backward <- BackwardIter(data,time,individual,transition)
  
  num <- forward[[time]] * backward[[time]] * (1 - stayer_mat[individual,1] - stayer_mat[individual,2])
  denom <- CalcIndLikelihoodFast(data,individual,forward,stayer_mat)

  frac <- num/as.vector(denom)
  return(frac)
}
```




```{r}
ExpectedTransitionFast <- function(data,time,individual,transition,initial_state,new_state,forward,backward,stayer_mat){
  num <- forward[[time-1]][initial_state+1] * backward[[time]][new_state+1] * (1 - stayer_mat[individual,1] - stayer_mat[individual,2])
  if (!is.na(data[individual,time])){
    num <- num * transition[initial_state+1,new_state+1] * Classification(data[individual,time],new_state)
  } else {
    num <- num * transition[initial_state+1,new_state+1]
  }
  denom <- CalcIndLikelihoodFast(data,individual,forward,stayer_mat)
  return(num/denom)
}
```

```{r}
CalcTransitionPattern <- function(data,initial_probabilities,transition, freq_vec, stayer_mat){
  k <- numOfStates(data)
  num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
  
  for (i in 1:dim(data)[1]){
    forward <- ForwardIter(data,dim(data)[2],i,initial_probabilities, transition)
    backward <- BackwardIter(data,1,i,transition)
    for (j in 2:dim(data)[2]){
      for (l in 1:length(k)){
        for (m in 1:length(k)){
          num_matrix[l,m] <- num_matrix[l,m] + (ExpectedTransitionFast(data,j,i,transition,k[l],k[m],forward,backward,stayer_mat) * freq_vec[i])
        }
      }
    }
  }
  



  return(Normalize(num_matrix))
}
```

```{r}
CalcIndLikelihoodFast <- function(data, individual,forward, stayer_mat){
  forward_sum <- sum(forward[[dim(data)[2]]])

  likelihood <- stayer_mat[individual,1] + stayer_mat[individual,2] + ((1 - stayer_mat[individual,1] - stayer_mat[individual,2]) * forward_sum) 
  return(likelihood)
}
```

```{r}
#tends to 1 
#Could be a problem 
CalcStayer <- function(data,initial_probabilities, transition, stayer_mat){
  max_time <- dim(data)[2]
  for (i in 1:dim(data)[1]){
    forward <- ForwardIter(data,max_time,i,initial_probabilities, transition)
    if (var(data[i,], na.rm = TRUE) != 0){
      stayer_mat[i,1] <- 0
      stayer_mat[i,2] <- 0
    } else {
      if(max(data[i,], na.rm = TRUE) == 0){
        stayer_mat[i,1] <- stayer_mat[i,1]/(stayer_mat[i,1] + ((1 - stayer_mat[i,1])*sum(forward[[max_time]])))
        stayer_mat[i,2] <- 0
      } else {
        stayer_mat[i,1] <- 0
        stayer_mat[i,2] <- stayer_mat[i,2]/(stayer_mat[i,2] + ((1 - stayer_mat[i,2])*sum(forward[[max_time]])))
      }
    }
  }
  return(stayer_mat)
}
```

```{r}
Vec2Mat <- function(data, stayer_vec){
  stayer_mat <- matrix(0,dim(data)[1],2)
  for (i in 1:dim(data)[1]){
    max_val <- max(data[i,], na.rm = T)
    min_val <- min(data[i,], na.rm = T)
    
    if (max_val == 1 & min_val == 1){
      stayer_mat[i,2] <- stayer_vec[2]
    } 
    else if (max_val == 0 & min_val == 0){
      stayer_mat[i,1] <- stayer_vec[1]
    } 
  }
  return(stayer_mat)
}
```

```{r}
Mat2Vec <- function(stayer_mat){
  stayer_vec <- c(max(stayer_mat[,1]), max(stayer_mat[,2]))
  return(stayer_vec)
}
```

```{r}
CalcLikelihoodPattern <- function(data, initial_probabilities,transition, freq_vec, stayer_mat){
  likelihood_sum <- 0
  for (i in 1:dim(data)[1]){
    likelihood <- log(CalcIndLikelihood(data,i,initial_probabilities,transition,stayer_mat)) * freq_vec[i]
    likelihood_sum <- likelihood_sum + likelihood
  }
  return(likelihood_sum)
}
```


```{r}
CalcIndLikelihood <- function(data, individual, initial_probabilities,transition, stayer_mat){
  forward <- ForwardIter(data,dim(data)[2],individual,initial_probabilities,transition)
  forward_sum <- sum(forward[[dim(data)[2]]])
  
  likelihood <- stayer_mat[individual,1] + stayer_mat[individual,2] + ((1 - stayer_mat[individual,1] - stayer_mat[individual,2]) * forward_sum)
  return(likelihood)
}
```

```{r}
CalcYiPattern <- function(data,time, initial_probabilities, transition, freq_vec,stayer_mat){
  k <- numOfStates(data)
  prob_list <- numeric(length(k))
  max_time <- dim(data)[2]
  for (i in 1:dim(data)[1]){
    forward <- ForwardIter(data,max_time,i,initial_probabilities, transition)
   
    backward <- BackwardIter(data,1,i,transition)
    
    mover <- forward[[time]] * backward[[time]] * (1 - stayer_mat[i,1] - stayer_mat[i,2])  / CalcIndLikelihoodFast(data,i,forward,stayer_mat)

    
    
    for (j in k){
      prob_list[j+1] <- prob_list[j+1] + (mover[j+1] * freq_vec[i])
    }
  }
  return(prob_list/sum(prob_list))
} 
```

```{r}
all_patterns <- as.data.frame(GetPatterns(catch_data))
unique_patterns <- as.data.frame(table(all_patterns))

pattern_list <- Pattern2Data(unique_patterns)
pattern_data <- pattern_list[[1]]
freq_vec <- pattern_list[[2]]

```

```{r}
#NEGATIVE LIKELIHOOD 
init <- InitialProbPattern(pattern_data,freq_vec)
tran <- TransitionProbPattern(pattern_data,freq_vec)
stayer_mat <- matrix(0,dim(pattern_data)[1],2)
old_likelihood <- CalcLikelihoodPattern(pattern_data,init,tran,freq_vec,stayer_mat)


init <- CalcYiPattern(pattern_data,1,init,tran,freq_vec,stayer_mat)
tran <- CalcTransitionPattern(pattern_data,init,tran,freq_vec,stayer_mat)
# stayer_mat <- CalcStayer(pattern_data,tran, freq_vec)
likelihood <- CalcLikelihoodPattern(pattern_data,init,tran,freq_vec,stayer_mat)

print(likelihood - old_likelihood)

while ((likelihood - old_likelihood) > 0.001){
  old_likelihood <- likelihood

  init <- CalcYiPattern(pattern_data,1,init,tran,freq_vec,stayer_mat)
  tran <- CalcTransitionPattern(pattern_data,init,tran,freq_vec,stayer_mat)
  # stayer_mat <- CalcStayer(pattern_data,tran,freq_vec,stayer_mat)
  likelihood <- CalcLikelihoodPattern(pattern_data,init,tran,freq_vec,stayer_mat)
  
  print(likelihood - old_likelihood)
}
```
