---
title: "State Project Data Sim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
numOfStates <- function(data){
  return(c(0:1))
}
```

```{r}
#Generates data
#n is number of individuals
#t is number of time points
#p is the proportion of stayers in the zero state 
GenerateAll <- function(n,t,p0,p1){
  #Stayer_vec_true is a vector where a 0/1 at the ith index says that individual i is either a mover/stayer
  stayer_vec_true <- GenerateMS(n,p0,p1)
  #data_mat will be the created data matrix
  data_mat <- matrix(0L, nrow = n, ncol = t)
  
  #Creates only the initial values for the data
  for (i in 1:n){
    #only enters this if statement if mover
    #As data was initialized to all 0's dont need to change stayer data
    if (stayer_vec_true[i] == 0){
      #Have to add a -1 at the end so we end up with a state space of 0/1 rather than 1/2
      data_mat[i,1] <- which(rmultinom(1,1,init_initial) == 1) - 1
    } else if (stayer_vec_true[i] == 2){
      data_mat[i,1] <- 1
    }
  }
  
  #Creates the rest of the data
  for (i in 1:n){
    #starts at 2 since we already created the initial values
    for (j in 2:t){
      #similar as above, only enter if mover
      if(stayer_vec_true[i] == 0){
        #P_current is the row of the transition matrix corresponding to the state at time j-1
        p_current <- tran_initial[data_mat[i,j-1]+1,]
        
        #creates the next state at time j depending only on the state at time j-1
        data_mat[i,j] <- which(rmultinom(1,1,p_current) == 1) - 1
      } else if (stayer_vec_true[i] == 2){
        data_mat[i,j] <- 1
      }
    }
  }
  return(list(data_mat, stayer_vec_true))
}
```

```{r}
#Generates a vector of 0/1
#A 1 at the ith index says that the ith individual is a stayer in the zero state 
#n and p are the same as above
#Used only in the function GenerateAll
GenerateMS <- function(n,p0,p1){

  
  stayer_vec <- numeric(n)
  for (i in 1:n){
    rand <- runif(1)
    if (rand < p0){
      stayer_vec[i] <- 1
    } else if (rand < (p0+p1)){
      stayer_vec[i] <- 2
    } 
  }
  return(stayer_vec)
}
```

```{r}
GetPatterns <- function(states,stayer_mat){
  library(plyr)
  options(scipen = 999)
  vals <- rep(NaN,dim(states)[1])
  for (i in 1:dim(states)[1]){
    val <- ""
    for(j in 1:dim(states)[2]){
      if (!is.na(states[i,j])){
        states_val <- states[i,j] 
      } else {
        states_val <- 2 
      }
      val <- paste0(val, states_val)
    }
    if (!missing(stayer_mat)){
      val <- paste0(val,stayer_mat[i])
    }
    
    vals[i] <- val
  }
  return(vals)
}
```

```{r}
Pattern2Data <- function(unique_patterns, stayer_mat){
  #SHOULD BE 32
  time_length <- nchar(as.character(unique_patterns$all_patterns[[1]]))
  n <- dim(unique_patterns)[1]
  state_mat <- matrix(NaN,n,time_length)
  freq_vec <- numeric(n)
  stayer_mat <- numeric(n)
  for (i in 1:n){
    freq_vec[i] <- unique_patterns$Freq[[i]]
    pattern <- unique_patterns$all_patterns[[i]]
    
    if (!missing(stayer_mat)){
      #stayer_mat[i] <- as.integer(substr(pattern, years_to_impute,years_to_impute))
    }
    
    for (time in 1:time_length){
      new_val <- as.integer(substr(pattern, time,time))
      if (new_val == 2){
        new_val <- NaN
      }
      state_mat[i,time] <- new_val
    }
  }
  if (!missing(stayer_mat)){
    return(list(state_mat, freq_vec,stayer_mat))
  }
  return(list(state_mat, freq_vec))
}

```

```{r}
#Normalizes the rows of a matrix to sum to 1
#Used only in transition matrix calculation
Normalize <- function(data){
  for (i in 1:dim(data)[1]){
    if (sum(data[i,],na.rm = TRUE) != 0){
      data[i,] <- data[i,]/sum(data[i,])
    }
  }
  return(data)
}
```

```{r}
InitialProbPattern <- function(data,stayer_vec){

  k <- numOfStates(data)
  init_prob <- numeric(length(k))
  
  for (i in 1:dim(data)[1]){
    if (!is.na(data[i,1])){
      if (stayer_vec[i] == 0){
        init_prob[data[i,1] + 1] <- (init_prob[data[i,1]+1] + 1)
      }
    }
  }
  
  return(init_prob/sum(init_prob))
}
```

```{r}
#Creates a transition matrix from a data matrix
#idea is to for loop thru both dimensions of the matrix
#The transition matrix at (i,j) is increased by one every time the data transitions from i to j
#Normalized sum of rows to 1 at the end
TransitionProbPattern <- function(data, stayer_vec){
  
  k <- numOfStates(data)
  tran <- matrix(0L, nrow = length(k), ncol = length(k))

  for (i in 1:dim(data)[1]){
    for (j in 1:(dim(data)[2] - 1)){
      if (stayer_vec[i] == 0){
        if (data[i,j] == 0){
          if (data[i,j+1] == 0){
            tran[1,1] <- tran[1,1] +1
          } else {
            tran[1,2] <- tran[1,2] + 1
          }
        } else {
          if (data[i,j+1] == 0){
            tran[2,1] <- tran[2,1] + 1
          } else {
            tran[2,2] <- tran[2,2] + 1
          }
        }
      }
    }
  }

  return(Normalize(tran))
}

```




```{r}
#Sets intial initial and transition parameters
#I played around with these 
r_0 <- .6
init_initial <- c(r_0, 1 - r_0)

p_00 <- .98
p_11 <- .98
tran_initial <- t(matrix(c(p_00, 1 - p_00, 1- p_11, p_11),2,2))

#Set initial parameters
#I played around with these 
n <- 4000
t <- 31
p0 <- .25
p1 <- .15

#Creates Data
all_data <- GenerateAll(n,t,p0,p1)
ms_data <- all_data[[1]]
stayer_vec_true <- all_data[[2]]

ms_data_obs <- ms_data

#Calculate True parameters
#Starts at the (n*p) + 1 row as thats the first mover individual
#Does not include the stayers in parameter calculation
ms_init <- InitialProbPattern(ms_data,stayer_vec_true)
ms_tran <- TransitionProbPattern(ms_data,stayer_vec_true)

#Calculates number of individuals where all the X's are 0's
zero_count <- 0
one_count <- 0
for (ind in 1:dim(ms_data)[1]){
  if (max(ms_data[ind,]) == 0){
    zero_count <- zero_count + 1
  }
  
  if (min(ms_data[ind,]) == 1){
    one_count <- one_count + 1
  }
}

#This is the (number of zeros - expected number of zeros if there were no stayers)/number of individuals
ms_stayer <- c((zero_count -  n*ms_init[1]*ms_tran[1,1]^(t-1))/n, (one_count -  n*ms_init[2]*ms_tran[2,2]^(t-1))/n)
ms_stayer[ms_stayer < 0] <- 0


ms_data_obs[,2:6] <- NaN
ms_data_obs[,8:12] <- NaN
ms_data_obs[,14:18] <- NaN
ms_data_obs[,20:24] <- NaN
ms_data_obs[,26:30] <- NaN

all_patterns <- as.data.frame(GetPatterns(ms_data_obs))
unique_patterns <- as.data.frame(table(all_patterns))

pattern_list <- Pattern2Data(unique_patterns)
state_pattern <- pattern_list[[1]]
freq_vec <- pattern_list[[2]]

```


